#!/bin/bash

LOCATION=southeastasia
MY_RG=daz-mysql-rg
MYSQL_NAME=mysqlserver4demo
DBADMIN=myadmin
DBPASSWORD=ssssssshhhhhhhss

# https://docs.microsoft.com/en-us/azure/mysql/howto-server-parameters
# https://docs.microsoft.com/en-us/azure/mysql/overview

az group create --name $MY_RG --location $LOCATION

az mysql server create \
  --name $MYSQL_NAME \
  --resource-group $MY_RG \
  --location $LOCATION \
  --admin-user $DBADMIN \
  --admin-password $DBPASSWORD \
  --performance-tier Basic \
  --compute-units 50

# Check the value of *innodb_lock_wait_timeout*
az mysql server configuration show \
   --resource-group $MY_RG \
   --server-name $MYSQL_NAME \
   --name innodb_lock_wait_timeout

# Set value of *innodb_lock_wait_timeout*
az mysql server configuration set \
   --resource-group $MY_RG \
   --server-name $MYSQL_NAME \
   --name innodb_lock_wait_timeout \
   --value 120

az mysql server configuration list --resource-group $MY_RG --server $MYSQL_NAME

az mysql server configuration show --name slow_query_log --resource-group $MY_RG --server $MYSQL_NAME
az mysql server configuration set --name slow_query_log --resource-group $MY_RG --server $MYSQL_NAME --value ON
az mysql server configuration set --name long_query_time --resource-group myresourcegroup --server myserver4demo --value 10

az mysql server firewall-rule create --resource-group $MY_RG --server $MYSQL_NAME --name AllowAll --start-ip-address 0.0.0.0 --end-ip-address 255.255.255.255

az mysql server update -g $MY_RG -n $MYSQL_NAME --ssl-enforcement Disabled

mysql --host $MYSQL_NAME.mysql.database.azure.com --user $DBADMIN@$MYSQL_NAME -p

# Display and then download MySQL Logs
az mysql server-logs list --resource-group daz-mysql-rg --server mysqlserver4demo
az mysql server-logs download --name 20170414-myserver4demo-mysql.log --resource-group daz-mysql-rg --server mysqlserver4demo

az mysql server delete --name $MYSQL_NAME --resource-group $MY_RG

az group delete --name $MY_RG --no-wait --yes
